version: '3.3'

services:
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - local

  basket_api:
    image: basket_api
    ports:
      - "5000:5000"
    networks:
      - local
    environment:
      REDIS_CONN_STRING: redis,6379,None
    
  
networks:
  local: